### ISSUE TITLE
Internal state of cell

### ISSUE THREAD

**Issue by Dylanflini** [Dylanflini/buscaminas-typescript#7]
The use cases functions can’t return information about where are the bombs in the board, the **bombs model** and **neighbors bombs counter** should be internal state save in database.

For this reason I think that **cell model** needs a new property, it could be called **state** having 3 possible values: undefined, “IS_BOMB” and “IS_NOT_BOMB”. Also needs a property for the quantity of bombs around the cell.

**Comment by danielglobant** [comment]
This makes me think that there is a `PublicBoard` and `PrivateBoard`, what can be shown to the user in the `PublicBoard` ?

**Comment by Dylanflini** [comment]
this:
  flags_available: number;
  bombs_available: number;
  rows: number;
  columns: number;
  cells: CellModel[];
  flags: FlagModel[];

**Comment by danielglobant** [comment]
```

export interface PublicBoardModel extends Omit<BoardModel, 'neighBorsBombsCounter' | 'bombs'> {
 
}

```

**Comment by Dylanflini** [comment]
Now I think about it, rows and columns is not necessary to the user, because is data that they provides

**Comment by danielglobant** [comment]
"
Now I think about it, rows and columns is not necessary to the user, because is data that they provide at the moment to create board
" ->

```
export interface PublicBoardModel
  extends Omit<
    BoardModel,
    'neighBorsBombsCounter' | 'bombs' | 'bombs_available' | 'columns' | 'rows'
  > {
}

```

**Comment by Dylanflini** [comment]
> 

a
